-- migrate:up
CREATE TABLE transaction (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    corporate_id UUID NOT NULL REFERENCES corporate(id),
    account_id UUID NOT NULL REFERENCES account(id), 
    dest_acc_no VARCHAR(50),
    dest_acc_name VARCHAR(100),
    amount NUMERIC(20,2),
    transaction_type VARCHAR(50),
    trrefn VARCHAR(50),
    sequence_journal VARCHAR(50),
    remarks TEXT,
    note TEXT,
    core_request_payload jsonb,
    core_response_payload jsonb,
    e_channel_request_payload jsonb,
    e_channel_response_payload jsonb,
    status VARCHAR(20),
    fee NUMERIC(20,2),
    status_code VARCHAR(20),
    seq_no VARCHAR(50),
    dest_bank_code VARCHAR(50),
    trx_successed_at TIMESTAMPTZ,
    icon_menu VARCHAR(50),
    icon    VARCHAR(50),
    icon_id   UUID REFERENCES icon (id),
    additional_data TEXT,
    destination_saku_id UUID,
    destination_saku_type VARCHAR(100),
    destination_address VARCHAR(50),
    purpose VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    failure_reason VARCHAR(255),
    user_authorization_id UUID REFERENCES user_authorization (id)
);

CREATE TABLE IF NOT EXISTS sequence_transfer (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    seq_no VARCHAR(20) NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount NUMERIC(20,2) NOT NULL,
    src_acc_no VARCHAR(50) NOT NULL,
    dest_acc_no VARCHAR(50) NOT NULL,
    src_acc_name VARCHAR(100) NOT NULL,
    dest_acc_name VARCHAR(100) NOT NULL,
    bi_fast_purpose_type VARCHAR(50) NOT NULL,
    transaction_type VARCHAR(50) NOT NULL,
    cif_dest VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL
);